networks:
  app_default:
    external: false

configs:
  nginx_conf:
    external: true

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
      - "8087:81"
    networks:
      - app_default
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
        
        
        
  postgres:
    image: krsvaaa/postgres:latest
    ports:
      - "5432:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    networks:
      - app_default
    volumes:
      - app:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager

  rabbitmq:
    image: krsvaaa/rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      TZ: "Europe/Moscow"
    networks:
      - app_default

  session-service:
    image: krsvaaa/session-service:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      TZ: "Europe/Moscow"
    networks:
      - app_default
    deploy:
      placement:
        constraints:
          - node.role == manager

  hotel-service:
    image: krsvaaa/hotel-service:latest
    ports:
      - "8082:8082"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: hotels_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Moscow"
    networks:
      - app_default

  payment-service:
    image: krsvaaa/payment-service:latest
    ports:
      - "8084:8084"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Moscow"
    networks:
      - app_default

  loyalty-service:
    image: krsvaaa/loyalty-service:latest
    ports:
      - "8085:8085"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: balances_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Moscow"
    networks:
      - app_default

  report-service:
    image: krsvaaa/report-service:latest
    ports:
      - "8086:8086"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: statistics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      TZ: "Europe/Moscow"
    networks:
      - app_default

  booking-service:
    image: krsvaaa/booking-service:latest
    ports:
      - "8083:8083"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: reservations_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
      TZ: "Europe/Moscow"
    networks:
      - app_default

  gateway-service:
    image: krsvaaa/gateway-service:latest
    environment:
      SESSION_SERVICE_HOST: session-service
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking-service
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report-service
      REPORT_SERVICE_PORT: 8086
      TZ: "Europe/Moscow"
    networks:
      - app_default
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  app:

